/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "NamWiki",
  "tagline": "Learn Namada: Privacy-first blockchain education",
  "favicon": "img/favicon.ico",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "url": "https://namwiki.xyz",
  "baseUrl": "/zh/",
  "trailingSlash": false,
  "organizationName": "Jules0x-xyz",
  "projectName": "namwiki",
  "deploymentBranch": "gh-pages",
  "onBrokenLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "es",
      "pt",
      "fr",
      "zh"
    ],
    "localeConfigs": {
      "en": {
        "label": "English",
        "direction": "ltr"
      },
      "es": {
        "label": "Español",
        "direction": "ltr"
      },
      "pt": {
        "label": "Português",
        "direction": "ltr"
      },
      "fr": {
        "label": "Français",
        "direction": "ltr"
      },
      "zh": {
        "label": "中文",
        "direction": "ltr"
      }
    },
    "path": "i18n"
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/Jules0x-xyz/namwiki/edit/main/",
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true,
          "breadcrumbs": true
        },
        "blog": {
          "showReadingTime": true,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "editUrl": "https://github.com/Jules0x-xyz/namwiki/edit/main/",
          "blogTitle": "NamWiki Blog",
          "blogDescription": "Latest updates, tutorials and news from the Namada community",
          "blogSidebarTitle": "Recent Posts",
          "blogSidebarCount": 10,
          "onInlineTags": "warn",
          "onInlineAuthors": "warn",
          "onUntruncatedBlogPosts": "warn"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/namwiki-social-card.png",
    "metadata": [
      {
        "name": "keywords",
        "content": "namada, privacy, blockchain, masp, zk-snarks, crypto, education"
      },
      {
        "name": "twitter:card",
        "content": "summary_large_image"
      },
      {
        "name": "author",
        "content": "NamWiki Community"
      }
    ],
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "navbar": {
      "title": "NamWiki",
      "logo": {
        "alt": "NamWiki Logo",
        "src": "img/logo.svg"
      },
      "hideOnScroll": false,
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "mainSidebar",
          "position": "left",
          "label": "Learn"
        },
        {
          "type": "dropdown",
          "label": "Guides",
          "position": "left",
          "items": [
            {
              "label": "Wallets",
              "to": "/docs/guides/wallets/install-namada-extension"
            },
            {
              "label": "Transactions",
              "to": "/docs/guides/transactions/buy-nam"
            },
            {
              "label": "Staking",
              "to": "/docs/guides/staking/understanding-staking"
            },
            {
              "label": "Governance",
              "to": "/docs/guides/governance/vote-on-proposals"
            }
          ]
        },
        {
          "to": "/docs/concepts/masp-explained",
          "label": "Concepts",
          "position": "left"
        },
        {
          "to": "/docs/resources/glossary",
          "label": "Resources",
          "position": "left"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "to": "/videos",
          "label": "Videos",
          "position": "left"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "href": "https://github.com/Jules0x-xyz/namwiki",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Learn",
          "items": [
            {
              "label": "Getting Started",
              "to": "/docs/getting-started/what-is-namada"
            },
            {
              "label": "Guides",
              "to": "/docs/guides/wallets/install-namada-extension"
            },
            {
              "label": "Concepts",
              "to": "/docs/concepts/masp-explained"
            },
            {
              "label": "FAQ",
              "to": "/docs/resources/faq"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Discord",
              "href": "https://discord.gg/namada"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/namwiki_xyz"
            },
            {
              "label": "Telegram",
              "href": "https://t.me/namwiki"
            },
            {
              "label": "YouTube",
              "href": "https://youtube.com/@namwiki"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Glossary",
              "to": "/docs/resources/glossary"
            },
            {
              "label": "Ecosystem Tools",
              "to": "/docs/resources/ecosystem-tools"
            },
            {
              "label": "Block Explorers",
              "to": "/docs/resources/block-explorers"
            },
            {
              "label": "Videos",
              "to": "/videos"
            }
          ]
        },
        {
          "title": "Contribute",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/Jules0x-xyz/namwiki"
            },
            {
              "label": "How to Contribute",
              "to": "/docs/contributing/how-to-contribute"
            },
            {
              "label": "Content Guidelines",
              "to": "/docs/contributing/content-guidelines"
            },
            {
              "label": "Blog Submissions",
              "to": "/docs/contributing/blog-submissions"
            }
          ]
        }
      ],
      "copyright": "NamWiki - Open source Namada education. Contact: hello@namwiki.xyz"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "json",
        "toml",
        "rust"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
